apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
  # namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: kai-wei-mo/auth:latest
---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  # namespace: default
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: auth-port